name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          coverage run -m unittest test_tutorial.py
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          pip install coveralls
          ls -la
          coveralls --verbose --service=github-actions

